import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)


def build_case_pdf(case: dict) -> bytes:
    """case is the same dict shape returned by GET /api/cases/{id}."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=16, textColor=colors.HexColor("#1a2b4c"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=12, textColor=colors.HexColor("#1a2b4c"), spaceBefore=10)
    body = styles["BodyText"]

    story = []
    story.append(Paragraph("Karnataka Police Department — FIR Case Report", title_style))
    story.append(Paragraph("CONFIDENTIAL — For official use only", ParagraphStyle("small", parent=body, textColor=colors.grey, fontSize=8)))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#1a2b4c")))
    story.append(Spacer(1, 12))

    meta_rows = [
        ["Crime No.", case.get("crime_no", "-"), "Case No.", case.get("case_no", "-")],
        ["Registered", case.get("registered_date", "-"), "Status", case.get("status", "-")],
        ["Category", case.get("category", "-"), "Gravity", case.get("gravity", "-")],
        ["Crime Head", case.get("crime_head", "-"), "Sub-Head", case.get("crime_sub_head", "-")],
        ["Police Station", case.get("station", "-"), "Investigating Officer", case.get("officer", "-")],
        ["Court", case.get("court", "-"), "", ""],
    ]
    t = Table(meta_rows, colWidths=[90, 150, 110, 130])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#dddddd")),
    ]))
    story.append(t)
    story.append(Spacer(1, 10))

    story.append(Paragraph("Brief Facts", h2))
    story.append(Paragraph(case.get("brief_facts", "-") or "-", body))

    if case.get("acts"):
        story.append(Paragraph("Acts & Sections Invoked", h2))
        rows = [["Act", "Section"]] + [[a["act"], a["section"]] for a in case["acts"]]
        at = Table(rows, colWidths=[240, 240])
        at.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2b4c")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#dddddd")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(at)

    if case.get("victims"):
        story.append(Paragraph("Victims", h2))
        rows = [["Name", "Age", "Gender"]] + [[v["name"], str(v["age"]), v["gender"]] for v in case["victims"]]
        vt = Table(rows, colWidths=[240, 100, 140])
        vt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#7a1f1f")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#dddddd")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(vt)

    if case.get("accused"):
        story.append(Paragraph("Accused", h2))
        rows = [["ID", "Name", "Age", "Gender", "Arrested?"]] + [
            [a["person_id"], a["name"], str(a["age"]), a["gender"], "Yes" if a["arrested"] else "No"]
            for a in case["accused"]
        ]
        act = Table(rows, colWidths=[40, 190, 60, 70, 120])
        act.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3a3a3a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#dddddd")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(act)

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd")))
    story.append(Paragraph("Generated by KSP Datathon 2026 Prototype Dashboard — synthetic demo data.",
                            ParagraphStyle("footer", parent=body, fontSize=7, textColor=colors.grey)))

    doc.build(story)
    return buf.getvalue()


def build_chat_pdf(messages: list, language: str = "en") -> bytes:
    """messages: [{role: 'user'|'assistant', text: str, timestamp: str}, ...]"""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=16, textColor=colors.HexColor("#1a2b4c"))
    user_style = ParagraphStyle("User", parent=styles["BodyText"], backColor=colors.HexColor("#eef1f8"),
                                 borderPadding=6, spaceBefore=8, spaceAfter=2)
    bot_style = ParagraphStyle("Bot", parent=styles["BodyText"], backColor=colors.HexColor("#fbf3df"),
                                borderPadding=6, spaceBefore=2, spaceAfter=8)
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=8, textColor=colors.grey)

    story = [
        Paragraph("KSP FIR Dashboard — Chatbot Conversation Export", title_style),
        Spacer(1, 4),
        HRFlowable(width="100%", color=colors.HexColor("#1a2b4c")),
        Spacer(1, 10),
    ]
    for m in messages:
        who = "You" if m.get("role") == "user" else "Assistant"
        style = user_style if m.get("role") == "user" else bot_style
        ts = f" — {m['timestamp']}" if m.get("timestamp") else ""
        text = (m.get("text") or "").replace("\n", "<br/>")
        story.append(Paragraph(f"<b>{who}{ts}:</b><br/>{text}", style))

    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd")))
    story.append(Paragraph("Generated by KSP Datathon 2026 Prototype Dashboard — synthetic demo data.", small))
    doc.build(story)
    return buf.getvalue()
